# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=60, unique=True)),
                ('access_token', models.CharField(max_length=120)),
                ('access_token_secret', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=60, unique=True)),
                ('last_updated', models.DateTimeField()),
                ('followed_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.AuthTokens')),
            ],
        ),
    ]
