# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-13 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=60, unique=True)),
                ('access_token', models.CharField(max_length=120)),
                ('access_token_secret', models.CharField(max_length=120)),
            ],
        ),
    ]
