# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 12:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_urlshared_cleaned_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='me_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='account_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='urlshared',
            name='url_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='urlshared',
            name='url_shared',
            field=models.DateTimeField(),
        ),
    ]
