# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 10:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20170205_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationToken',
            fields=[
                ('uuid', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('token_for', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.TwitterAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
